### ISSUE TITLE
xvc file

### ISSUE THREAD

**Issue by moti477** [skydevil88/XboxDownload#59]
Hello.
1. Can I open / install xvc file with powershell?
2. How can I open / install xvc file in pc or xbox?

**Comment by skydevil88** [comment]
1.you can not open .xvc file with PowerShell, because .xvc is Console Games

2.you can upload to Xbox through PC , 
refer to this: https://www.youtube.com/watch?v=DD4gtkNIOfs

3. you can also convert Xbox External Hard Drive to PC Mode, and then copy the file
![image](https://user-images.githubusercontent.com/60030602/224718108-7ec3057f-1610-41a2-a69b-961e6e6a489b.png)
refer to this: https://www.youtube.com/watch?v=0sWetv3Ko08

**Comment by skydevil88** [comment]
Sorry, i am not sure  could it do with xbox emulator for PC, i have not try run on emulator before.
